import os

def borrarPantalla():
    if os.name == "posix":
        os.system ("clear")
    elif os.name == "ce" or os.name == "nt" or os.name == "dos":
        os.system ("cls")

separador = ("-" * 30)

def menuPrincipal():
    print("\n-- MENÚ PRINCIPAL --")
    print("[1] Presupuesto de Ventas")
    print("[2] Determinacion del saldo de Clientes y Flujo de Entradas")
    print("[3] Presupuesto de Produccion")
    print("[4] Presupuesto de Requerimiento de Materiales")
    print("[5] Presupuesto de Compra de Materiales")
    print("[6] Determinacion del saldo de Proveedores y Flujo de Salidas")
    print("[7] Presupuesto de Mano de Obra Directa")
    print("[8] Presupuesto de Gastos Indirectos de Fabricacion")
    print("[9] Presupuesto de Gastos de Operacion")
    print("[10] Determinacion del Costo Unitario de Productos Terminados")
    print("[11] Valuacion de Inventarios Finales")
    print("[12] Estado de Costo de Producción y Ventas")
    print("[13] Estado de Resultados")
    print("[14] Estado de Flujo de Efectivo")
    print("[15] Balance General")
    print("[0] Salir")

while True:
    borrarPantalla()
    menuPrincipal()
    opcion = int(input("Elegir una opcion: "))
    if opcion == 1:
        borrarPantalla()
        print("-1- Presupuesto de Ventas")
        print("Producto CL")
        print("SEMESTRE 1")
        uni_a_ve1CL = int(input("Unidades a vender semestre 1: "))
        precio_de_ve1CL = int(input("Precio de venta semestre 1: "))
        imp_de_ve1CL = (uni_a_ve1CL * precio_de_ve1CL)
        print(f"El importe de venta del semestre 1 del Producto CL es {imp_de_ve1CL}")
        print("SEMESTRE 2")
        uni_a_ve2CL = int(input("Unidades a vender semestre 2: "))
        precio_de_ve2CL = int(input("Precio de venta semestre 2: "))
        imp_de_ve2CL = (uni_a_ve2CL * precio_de_ve2CL)
        print(f"El importe de venta del semestre 2 del Producto CL es {imp_de_ve2CL}")
        print(f"El importe de venta total del 2016 es {imp_de_ve1CL + imp_de_ve2CL}")
        print(separador)

        print("Producto CE")
        print("SEMESTRE 1")
        uni_a_ve1CE = int(input("Unidades a vender semestre 1: "))
        precio_de_ve1CE = int(input("Precio de venta semestre 1: "))
        imp_de_ve1CE = (uni_a_ve1CE * precio_de_ve1CE)
        print(f"El importe de venta del semestre 1 del Producto CE es {imp_de_ve1CE}")
        print("SEMESTRE 2")
        uni_a_ve2CE = int(input("Unidades a vender semestre 2: "))
        precio_de_ve2CE = int(input("Precio de venta semestre 2: "))
        imp_de_ve2CE = (uni_a_ve2CE * precio_de_ve2CE)
        print(f"El importe de venta del semestre 2 del Producto CE es {imp_de_ve2CE}")
        print(f"El importe de venta total del 2016 es {imp_de_ve1CE + imp_de_ve2CE}")
        print(separador)

        print("Producto CR")
        print("SEMESTRE 1")
        uni_a_ve1CR = int(input("Unidades a vender semestre 1: "))
        precio_de_ve1CR = int(input("Precio de venta semestre 1: "))
        imp_de_ve1CR = (uni_a_ve1CR * precio_de_ve1CR)
        print(f"El importe de venta del semestre 1 del Producto CR es {imp_de_ve1CR}")
        print("SEMESTRE 2")
        uni_a_ve2CR = int(input("Unidades a vender semestre 2: "))
        precio_de_ve2CR = int(input("Precio de venta semestre 2: "))
        imp_de_ve2CR = (uni_a_ve2CR * precio_de_ve2CR)
        print(f"El importe de venta del semestre 2 del Producto CR es {imp_de_ve2CR}")
        print(f"El importe de venta total del 2016 es {imp_de_ve1CR + imp_de_ve2CR}")

        Tot_Ventas_Sem1 = (imp_de_ve1CL+imp_de_ve1CE+imp_de_ve1CR)
        Tot_Ventas_Sem2 = (imp_de_ve2CL+imp_de_ve2CE+imp_de_ve2CR)
        print(f"El total de ventas por semestre (Semestre 1) es de {Tot_Ventas_Sem1}")
        print(f"El total de ventas por semestre (Semestre 2) es de {Tot_Ventas_Sem2}")
        print(f"El total de ventas por semestre es de {Tot_Ventas_Sem1 + Tot_Ventas_Sem2}")

    elif opcion == 2:
        borrarPantalla()
        print("-2- Determinacion del saldo de Clientes y Flujo de Entradas")
        saldo_clientes2015 = int(input("Ingrese el saldo de la cuenta CLIENTES del 31-Dic-2015: "))
        ventas_2016 = int(input("Ingrese las Ventas del 2016: "))
        total_clientes2016 = (saldo_clientes2015 + ventas_2016)
        print(f"El total de Clientes 2016' es {total_clientes2016}")
        print(f"El 100% Por cobranza del 2015 es {saldo_clientes2015}")
        cobranza_2016 = (ventas_2016 * 0.8)
        print(f"El 80% por cobranza del 2016 es {cobranza_2016}")
        entradas_2016 = (cobranza_2016 + saldo_clientes2015)
        print(f"El total de Entradas 2016 es {entradas_2016}")
        print(f"Saldo de Clientes 2016 es {total_clientes2016 - entradas_2016}")

    elif opcion == 3:
        borrarPantalla()
        print("-3- Presupuesto de Produccion")
        print("Producto CL")
        print("SEMESTRE 1")
        uni_a_venderCL1 = int(input("Unidades a vender del 1er semestre: "))
        in_final1CL = int(input("Inventario final del semestre 1: "))
        total_unidades1CL = (uni_a_venderCL1 + in_final1CL)
        print(f"El total de unidades del semestre 1 es {total_unidades1CL}")
        print(f"El inventario inicial del semestre 1 es {in_final1CL}")
        unidades_prodCL1 = (total_unidades1CL - in_final1CL)
        print(f"Las unidades a producir son del semestre 1 son {unidades_prodCL1}")

        print("SEMESTRE 2")
        uni_a_venderCL2 = int(input("Ingrese las unidades a vender del semestre 2: "))
        In_final2CL = int(input("Ingrese el inventario final del semestre 2: "))
        total_unidades2CL = (uni_a_venderCL2 + In_final2CL)
        print(f"El total de unidades del semestre 2 es {total_unidades2CL}")
        print(f"El inventario inicial del semestre 2 es {in_final1CL}")
        unidades_prodCL2 = (total_unidades2CL - in_final1CL)
        print(f"Las unidades a producir son del semestre 2 son {unidades_prodCL2}")

        print("Total 2016")
        tot_uds_TOT = (uni_a_venderCL1 + uni_a_venderCL2)
        print(f"Las unidades a vender en total son {tot_uds_TOT}")
        print(f"El inventario final total es {In_final2CL}")
        total_unidades = (tot_uds_TOT + In_final2CL)
        print(f"El total de unidades {total_unidades} ")
        print(f"El inventario inicial del total es {in_final1CL}")
        print(f"Las unidades a producir totales son {total_unidades - in_final1CL}")

        print(separador)

        print("Producto CE")
        print("SEMESTRE 1")
        uni_a_venderCE1 = int(input("Ingrese las unidades a vender del 1er semestre: "))
        in_final1CE = int(input("Ingrese el inventario final del semestre 1: "))
        total_unidades1CE = (uni_a_venderCE1 + in_final1CE)
        print(f"El total de unidades del semestre 1 es {total_unidades1CE}")
        print(f"El inventario inicial del semestre 1 es {in_final1CE}")
        unidades_prodCE1 = (total_unidades1CE - in_final1CE)
        print(f"Las unidades a producir son del semestre 1 son {unidades_prodCE1}")

        print("SEMESTRE 2")
        uni_a_venderCE2 = int(input("Ingrese las unidades a vender del semestre 2: "))
        In_final2CE = int(input("Ingrese el inventario final del semestre 2: "))
        total_unidades2CE = (uni_a_venderCE2 + In_final2CE)
        print(f"El total de unidades del semestre 2 es {total_unidades2CE}")
        print(f"El inventario inicial del semestre 2 es {in_final1CE}")
        unidades_prodCE2 = (total_unidades2CE - in_final1CE)
        print(f"Las unidades a producir son del semestre 2 son {unidades_prodCE2}")


        print("Total 2016")
        tot_uds_TOTCE = (uni_a_venderCE1 + uni_a_venderCE2)
        print(f"Las unidades a vender en total son {tot_uds_TOTCE}")
        print(f"El inventario final total es {In_final2CE}")
        Total_UnidadesCE = (tot_uds_TOTCE + In_final2CE)
        print(f"El total de unidades {Total_UnidadesCE} ")
        print(f"El inventario inicial del total es {in_final1CE}")
        print(f"Las unidades a producir totales son {Total_UnidadesCE - in_final1CE}")

        print(separador)

        print("Producto CR")
        print("SEMESTRE 1")
        uni_a_venderCR1 = int(input("Ingrese las unidades a vender del 1er semestre: "))
        In_final1CR = int(input("Ingrese el inventario final del semestre 1: "))
        total_unidades1CR = (uni_a_venderCR1 + In_final1CR)
        print(f"El total de unidades del semestre 1 es {total_unidades1CR}")
        print(f"El inventario inicial del semestre 1 es {In_final1CR}")
        Unidades_prodCR1 = (total_unidades1CR - In_final1CR)
        print(f"Las unidades a producir son del semestre 1 son {Unidades_prodCR1}")

        print("SEMESTRE 2")
        uni_a_venderCR2 = int(input("Ingrese las unidades a vender del semestre 2: "))
        In_final2CR = int(input("Ingrese el inventario final del semestre 2: "))
        total_unidades2CR = (uni_a_venderCR2 + In_final2CR)
        print(f"El total de unidades del semestre 2 es {total_unidades2CR}")
        print(f"El inventario inicial del semestre 2 es {In_final1CR}")
        Unidades_prodCR = (total_unidades2CR - In_final1CR)
        print(f"Las unidades a producir son del semestre 2 son {Unidades_prodCR}")

        print("Total 2016")
        tot_uds_TOTCR = (uni_a_venderCR1 + uni_a_venderCR2)
        print(f"Las unidades a vender en total son {tot_uds_TOTCR}")
        print(f"El inventario final total es {In_final2CR}")
        Total_UnidadesCR = (tot_uds_TOTCR + In_final2CR)
        print(f"El total de unidades {Total_UnidadesCR} ")
        print(f"El inventario inicial del total es {In_final1CR}")
        print(f"Las unidades a producir totales son {Total_UnidadesCR - In_final1CR}")
        print(separador)

    elif opcion == 4:
        borrarPantalla()
        print("-4- Presupuesto de Requerimiento de Materiales")
        print("Producto CL")
        print("Semestre 1")
        unidades_a_prodCL1 = int(input("Ingrese las unidades a producir del semestre 1: "))
        print("Material A")
        Requerimiento_materialA = float(input("Ingrese el requerimiento de material A: "))
        MaterialACL1 = (unidades_a_prodCL1 * Requerimiento_materialA)
        print(f"Total de Material A requerido {MaterialACL1}")
        print("Material B")
        Requerimiento_materialB = float(input("Ingrese el requerimiento de material B: "))
        MaterialBCL1 = (unidades_a_prodCL1 * Requerimiento_materialB)
        print(f"Total de Material B requerido {MaterialBCL1}")
        print("Material C")
        Requerimiento_materialC = float(input("Ingrese el requerimiento de material C: "))
        MaterialCCL1 = (unidades_a_prodCL1 * Requerimiento_materialC)
        print(f"Total de Material C requerido {MaterialCCL1}")

        print("Semestre 2")

        unidades_a_prodCL2 = int(input("Ingrese las unidades a producir del semestre 2: "))
        print("Material A")
        Requerimiento_materialA2 = float(input("Ingrese el requerimiento de material A: "))
        MaterialACL2 = (unidades_a_prodCL2 * Requerimiento_materialA2)
        print(f"Total de Material A requerido {MaterialACL2}")
        print("Material B")
        Requerimiento_materialB2 = float(input("Ingrese el requerimiento de material B: "))
        MaterialBCL2 = (unidades_a_prodCL2 * Requerimiento_materialB2)
        print(f"Total de Material B requerido {MaterialBCL2}")
        print("Material C")
        Requerimiento_materialC2 = float(input("Ingrese el requerimiento de material C: "))
        MaterialCCL2 = (unidades_a_prodCL2 * Requerimiento_materialC2)
        print(f"Total de Material C requerido {MaterialCCL2}")

        print("Total 2016")

        unidades_a_prodCLT = int(input("Ingrese las suma de unidades a producir de los semestres 1 y 2: "))
        print("Material A")
        Requerimiento_materialAT = float(input("Ingrese el requerimiento de material A: "))
        MaterialACLT = (unidades_a_prodCLT * Requerimiento_materialAT)
        print(f"Total de Material A requerido {MaterialACLT}")
        print("Material B")
        Requerimiento_materialBT = float(input("Ingrese el requerimiento de material B: "))
        MaterialBCLT = (unidades_a_prodCLT * Requerimiento_materialBT)
        print(f"Total de Material B requerido {MaterialBCLT}")
        print("Material C")
        Requerimiento_materialCT = float(input("Ingrese el requerimiento de material C: "))
        MaterialCCLT = (unidades_a_prodCLT * Requerimiento_materialCT)
        print(f"Total de Material C requerido {MaterialCCLT}")
        print(separador)

        print("Producto CE")
        print("Semestre 1")
        unidades_a_prodCE1 = int(input("Ingrese las unidades a producir del semestre 1: "))
        print("Material A")
        Requerimiento_materialACE = float(input("Ingrese el requerimiento de material A: "))
        MaterialACE1 = (unidades_a_prodCE1 * Requerimiento_materialACE)
        print(f"Total de Material A requerido {MaterialACE1}")
        print("Material B")
        Requerimiento_materialBCE = float(input("Ingrese el requerimiento de material B: "))
        MaterialBCE1 = (unidades_a_prodCE1 * Requerimiento_materialBCE)
        print(f"Total de Material B requerido {MaterialBCE1}")
        print("Material C")
        Requerimiento_materialCCE = float(input("Ingrese el requerimiento de material C: "))
        MaterialCCE1 = (unidades_a_prodCE1 * Requerimiento_materialCCE)
        print(f"Total de Material C requerido {MaterialCCE1}")

        print("Semestre 2")

        unidades_a_prodCE2 = int(input("Ingrese las unidades a producir del semestre 2: "))
        print("Material A")
        Requerimiento_materialACE2 = float(input("Ingrese el requerimiento de material A: "))
        MaterialACE2 = (unidades_a_prodCE2 * Requerimiento_materialACE2)
        print(f"Total de Material A requerido {MaterialACE2}")
        print("Material B")
        Requerimiento_materialBCE2 = float(input("Ingrese el requerimiento de material B: "))
        MaterialBCE2 = (unidades_a_prodCE2 * Requerimiento_materialBCE2)
        print(f"Total de Material B requerido {MaterialBCE2}")
        print("Material C")
        Requerimiento_materialCCE2 = float(input("Ingrese el requerimiento de material C: "))
        MaterialCCE2 = (unidades_a_prodCE2 * Requerimiento_materialCCE2)
        print(f"Total de Material C requerido {MaterialCCE2}")

        print("Total 2016")

        unidades_a_prodCET = int(input("Ingrese las suma de unidades a producir de los semestres 1 y 2: "))
        print("Material A")
        Requerimiento_materialACET = float(input("Ingrese el requerimiento de material A: "))
        MaterialACET = (unidades_a_prodCET * Requerimiento_materialACET)
        print(f"Total de Material A requerido {MaterialACET}")
        print("Material B")
        Requerimiento_materialBCET = float(input("Ingrese el requerimiento de material B: "))
        MaterialBCET = (unidades_a_prodCET * Requerimiento_materialBCET)
        print(f"Total de Material B requerido {MaterialBCET}")
        print("Material C")
        Requerimiento_materialCCET = float(input("Ingrese el requerimiento de material C: "))
        MaterialCCET = (unidades_a_prodCET * Requerimiento_materialCCET)
        print(f"Total de Material C requerido {MaterialCCET}")
        print(separador)

        print("Producto CR")
        print("Semestre 1")
        unidades_a_prodCR1 = int(input("Ingrese las unidades a producir del semestre 1: "))
        print("Material A")
        Requerimiento_materialACR = float(input("Ingrese el requerimiento de material A: "))
        MaterialACR1 = (unidades_a_prodCR1 * Requerimiento_materialACR)
        print(f"Total de Material A requerido {MaterialACR1}")
        print("Material B")
        Requerimiento_materialBCR = float(input("Ingrese el requerimiento de material B: "))
        MaterialBCR1 = (unidades_a_prodCR1 * Requerimiento_materialBCR)
        print(f"Total de Material B requerido {MaterialBCR1}")
        print("Material C")
        Requerimiento_materialCCR = float(input("Ingrese el requerimiento de material C: "))
        MaterialCCR1 = (unidades_a_prodCR1 * Requerimiento_materialCCR)
        print(f"Total de Material C requerido {MaterialCCR1}")

        print("Semestre 2")

        unidades_a_prodCR2 = int(input("Ingrese las unidades a producir del semestre 2: "))
        print("Material A")
        Requerimiento_materialACR2 = float(input("Ingrese el requerimiento de material A: "))
        MaterialACR2 = (unidades_a_prodCR2 * Requerimiento_materialACR2)
        print(f"Total de Material A requerido {MaterialACR2}")
        print("Material B")
        Requerimiento_materialBCR2 = float(input("Ingrese el requerimiento de material B: "))
        MaterialBCR2 = (unidades_a_prodCR2 * Requerimiento_materialBCR2)
        print(f"Total de Material B requerido {MaterialBCR2}")
        print("Material C")
        Requerimiento_materialCCR2 = float(input("Ingrese el requerimiento de material C: "))
        MaterialCCR2 = (unidades_a_prodCR2 * Requerimiento_materialCCR2)
        print(f"Total de Material C requerido {MaterialCCR2}")

        print("Total 2016")

        unidades_a_prodCRT = int(input("Ingrese las suma de unidades a producir de los semestres 1 y 2: "))
        print("Material A")
        Requerimiento_materialACRT = float(input("Ingrese el requerimiento de material A: "))
        MaterialACRT = (unidades_a_prodCRT * Requerimiento_materialACRT)
        print(f"Total de Material A requerido {MaterialACRT}")
        print("Material B")
        Requerimiento_materialBCRT = float(input("Ingrese el requerimiento de material B: "))
        MaterialBCRT = (unidades_a_prodCRT * Requerimiento_materialBCRT)
        print(f"Total de Material B requerido {MaterialBCRT}")
        print("Material C")
        Requerimiento_materialCCRT = float(input("Ingrese el requerimiento de material C: "))
        MaterialCCRT = (unidades_a_prodCRT * Requerimiento_materialCCRT)
        print(f"Total de Material C requerido {MaterialCCRT}")
        print("Total de Requerimientos (gramos)")
        print(f"1er Semestre Material A = {MaterialACL1 + MaterialACE1 + MaterialACR1}")
        print(f"1er Semestre Material B = {MaterialBCL1 + MaterialBCE1 + MaterialBCR1}")
        print(f"1er Semestre Material C = {MaterialCCL1 + MaterialCCE1 + MaterialCCR1}")
        print(separador)
        print(f"2do Semestre Material A = {MaterialACL2 + MaterialACE2 + MaterialACR2}")
        print(f"2do Semestre Material B = {MaterialBCL2 + MaterialBCE2 + MaterialBCR2}")
        print(f"2do Semestre Material C = {MaterialCCL2 + MaterialCCE2 + MaterialCCR2}")
        print(separador)
        print(f"Total Material A = {MaterialACLT + MaterialACET + MaterialACRT}")
        print(f"Total Material B = {MaterialBCLT + MaterialBCET + MaterialBCRT}")
        print(f"Total Material C = {MaterialCCLT + MaterialCCET + MaterialCCRT}")
        print(separador)

    elif opcion == 5:
        borrarPantalla()
        print("-5- Presupesto de Compra de Materiales")
        print("Mateial A")
        print("Semestre 1")
        requerimiento5_matA1 = int(input("Ingrese el requerimiento de materiales: "))
        inventariofinal_matA1 = int(input("Ingrese el inventario final: "))
        total5_matA1 = (requerimiento5_matA1 + inventariofinal_matA1)
        print(f"Total de materiales: {total5_matA1}")
        print(f"Inventario Inicial : {inventariofinal_matA1}")
        mat_acomprarA1 = (total5_matA1 - inventariofinal_matA1)
        print(f"El material a comprar es: {mat_acomprarA1}")
        precio_compaMatA1 = int(input("Ingrese el precio de compra: "))
        totalcompraMatA1 = (mat_acomprarA1 * precio_compaMatA1)
        print(f"Total de Material A en $ semestre 1: {totalcompraMatA1}")

        print("Semestre 2")
        requerimiento5_matA2 = int(input("Ingrese el requerimiento de materiales: "))
        inventariofinal_matA2 = int(input("Ingrese el inventario final: "))
        total5_matA2 = (requerimiento5_matA2 + inventariofinal_matA2)
        print(f"Total de materiales: {total5_matA2}")
        print(f"Inventario Inicial : {inventariofinal_matA1}")
        mat_acomprarA2 = (total5_matA2 - inventariofinal_matA1)
        print(f"El material a comprar es: {mat_acomprarA2}")
        precio_compaMatA2 = int(input("Ingrese el precio de compra: "))
        totalcompraMatA2 = (mat_acomprarA2 * precio_compaMatA2)
        print(f"Total de Material A en $ semestre 2: {totalcompraMatA2}")

        print("Total 2016")
        requerimiento5_matAT = int(input("Ingrese el requerimiento de materiales: "))
        inventariofinal_matAT = int(input("Ingrese el inventario final: "))
        total5_matAT = (requerimiento5_matAT + inventariofinal_matAT)
        print(f"Total de materiales: {total5_matAT}")
        print(f"Inventario Inicial : {inventariofinal_matA1}")
        mat_acomprarAT = (total5_matAT - inventariofinal_matA1)
        print(f"El material a comprar es: {mat_acomprarAT}")
        totalcompraMatAT = (totalcompraMatA1 + totalcompraMatA2)
        print(f"Total de Material en total $: {totalcompraMatAT}")
        print(separador)

        print("Mateial B")
        print("Semestre 1")
        requerimiento5_matB1 = int(input("Ingrese el requerimiento de materiales: "))
        inventariofinal_matB1 = int(input("Ingrese el inventario final: "))
        total5_matB1 = (requerimiento5_matB1 + inventariofinal_matB1)
        print(f"Total de materiales: {total5_matB1}")
        print(f"Inventario Inicial : {inventariofinal_matB1}")
        mat_acomprarB1 = (total5_matB1 - inventariofinal_matB1)
        print(f"El material a comprar es: {mat_acomprarB1}")
        precio_compaMatB1 = int(input("Ingrese el precio de compra: "))
        totalcompraMatB1 = (mat_acomprarB1 * precio_compaMatB1)
        print(f"Total de Material A en semestre 1 $: {totalcompraMatB1}")

        print("Semestre 2")
        requerimiento5_matB2 = int(input("Ingrese el requerimiento de materiales: "))
        inventariofinal_matB2 = int(input("Ingrese el inventario final: "))
        total5_matB2 = (requerimiento5_matB2 + inventariofinal_matB2)
        print(f"Total de materiales: {total5_matB2}")
        print(f"Inventario Inicial : {inventariofinal_matB1}")
        mat_acomprarB2 = (total5_matB2 - inventariofinal_matB1)
        print(f"El material a comprar es: {mat_acomprarB2}")
        precio_compaMatB2 = int(input("Ingrese el precio de compra: "))
        totalcompraMatB2 = (mat_acomprarB2 * precio_compaMatB2)
        print(f"Total de Material A en semestre 2 $: {totalcompraMatB2}")

        print("Total 2016")
        requerimiento5_matBT = int(input("Ingrese el requerimiento de materiales: "))
        inventariofinal_matBT = int(input("Ingrese el inventario final: "))
        total5_matBT = (requerimiento5_matBT + inventariofinal_matBT)
        print(f"Total de materiales: {total5_matBT}")
        print(f"Inventario Inicial : {inventariofinal_matB1}")
        mat_acomprarBT = (total5_matBT - inventariofinal_matB1)
        print(f"El material a comprar es: {mat_acomprarBT}")
        totalcompraMatBT = (totalcompraMatB1 + totalcompraMatB2)
        print(f"Total de Material en total $: {totalcompraMatBT}")
        print(separador)

        print("Mateial C")
        print("Semestre 1")
        requerimiento5_matC1 = int(input("Ingrese el requerimiento de materiales: "))
        inventariofinal_matC1 = int(input("Ingrese el inventario final: "))
        total5_matC1 = (requerimiento5_matC1 + inventariofinal_matC1)
        print(f"Total de materiales: {total5_matC1}")
        print(f"Inventario Inicial : {inventariofinal_matC1}")
        mat_acomprarC1 = (total5_matC1 - inventariofinal_matC1)
        print(f"El material a comprar es: {mat_acomprarC1}")
        precio_compaMatC1 = int(input("Ingrese el precio de compra: "))
        totalcompraMatC1 = (mat_acomprarC1 * precio_compaMatC1)
        print(f"Total de Material C en semestre 1 $: {totalcompraMatC1}")

        print("Semestre 2")
        requerimiento5_matC2 = int(input("Ingrese el requerimiento de materiales: "))
        inventariofinal_matC2 = int(input("Ingrese el inventario final: "))
        total5_matC2 = (requerimiento5_matC2 + inventariofinal_matC2)
        print(f"Total de materiales: {total5_matC2}")
        print(f"Inventario Inicial : {inventariofinal_matC1}")
        mat_acomprarC2 = (total5_matC2 - inventariofinal_matC1)
        print(f"El material a comprar es: {mat_acomprarC2}")
        precio_compaMatC2 = int(input("Ingrese el precio de compra: "))
        totalcompraMatC2 = (mat_acomprarC2 * precio_compaMatC2)
        print(f"Total de Material C en semestre 1 $: {totalcompraMatC2}")

        print("Total 2016")
        requerimiento5_matCT = int(input("Ingrese el requerimiento de materiales: "))
        inventariofinal_matCT = int(input("Ingrese el inventario final: "))
        total5_matCT = (requerimiento5_matCT + inventariofinal_matCT)
        print(f"Total de materiales: {total5_matCT}")
        print(f"Inventario Inicial : {inventariofinal_matC1}")
        mat_acomprarCT = (total5_matCT - inventariofinal_matC1)
        print(f"El material a comprar es: {mat_acomprarCT}")
        totalcompraMatCT = (totalcompraMatC1 + totalcompraMatC2)
        print(f"Total de Material en $: {totalcompraMatCT}")
        print(separador)
        comprastotalesSEM1 = (totalcompraMatA1 + totalcompraMatB1 + totalcompraMatC1)
        comprastotalesSEM2 = (totalcompraMatA2 + totalcompraMatB2 + totalcompraMatC2)
        comprastotalesTOT = (totalcompraMatAT + totalcompraMatBT + totalcompraMatCT)
        print(f"Compras totales semestre 1: {comprastotalesSEM1}")
        print(f"Compras totales semestre t: {comprastotalesSEM2}")
        print(f"Compras total (semestre 1 y 2): {comprastotalesTOT}")
        print(separador)

    elif opcion == 6:
        borrarPantalla()
        print("-6- Determinacion del saldo de Proveedores y Flujo de Salidas")
        saldo_proveedores2015 = int(input("Ingrese el saldo de la cuenta 'PROVEEDORES' del 31-Dic-2015: "))
        Compras_2016 = int(input("Ingrese las compras del 2016: "))
        total_proveedores2016 = (saldo_proveedores2015 + Compras_2016)
        print(f"El Total de Proveedores 2016': {total_proveedores2016}")
        print(f"El 100% Por cobranza del 2015: {saldo_proveedores2015}")
        cobranzaproveedores_2016 = (Compras_2016 * 0.5)
        print(f"El 50% Por cobranza del 2016: {cobranzaproveedores_2016}")
        salidasproveedores_2016 = (cobranzaproveedores_2016 + saldo_proveedores2015)
        print(f"El Total de Salidas 2016: {salidasproveedores_2016}")
        print(f"Saldo de Clientes 2016: {total_proveedores2016 - salidasproveedores_2016}")

    elif opcion == 7:
        borrarPantalla()
        print("-7- Presupuesto de Mano de Obra Directa")
        print("Producto CL")
        print("Semestre 1")
        un_a_p1 = float(input("Dime las unidades a producir del semestre 1: "))
        hr_p_u1 = float(input("Dime las horas requeridas por unidad del semestre 1: "))
        ttlhr1 = (un_a_p1 * hr_p_u1)
        print(f"El Total de horas requeridas del semestre 1 es: {ttlhr1}")
        cuoph1 = float(input("Dime la cuota por hora del semestre 1: "))
        imdm1 = (ttlhr1 * cuoph1)
        print(f"El Importe de M.O.D. del semestre 1 es: {imdm1}")

        print(separador)
        print("Semestre 2")
        un_a_p2 = float(input("Dime las unidades a producir del semestre 2: "))
        hr_p_u2 = float(input("Dime las horas requeridas por unidad del semestre 2: "))
        ttlhr2 = (un_a_p2 * hr_p_u2)
        print(f"El Total de horas requeridas del semestre 2 es: {ttlhr2}")
        cuoph2 = float(input("Dime la cuota por hora del semestre 2: "))
        imdm2 = (ttlhr2 * cuoph2)
        print(f"El Importe de M.O.D. del semestre 2 es: {imdm2}")

        print(separador)
        print("Año")
        un_a_pt = (un_a_p1 + un_a_p2)
        hr_p_ut = (hr_p_u1)
        ttlhrt = (un_a_pt * hr_p_ut)
        imdmt = (imdm1 + imdm2)
        print(f"El Total de horas requeridas del año es: {ttlhrt}")
        print(f"El Importe de M.O.D. del año es: {imdmt}")

        print(separador)
        print("Producto CE")
        print("Semestre 1")
        un_a_p1c = float(input("Dime las unidades a producir del semestre 1: "))
        hr_p_u1c = float(input("Dime las horas requeridas por unidad del semestre 1: "))
        ttlhr1c = (un_a_p1c * hr_p_u1c)
        print(f"El Total de horas requeridas del semestre 1 es: {ttlhr1c}")
        cuoph1c = float(input("Dime la cuota por hora del semestre 1: "))
        imdm1c = (ttlhr1c * cuoph1c)
        print(f"El Importe de M.O.D. del semestre 1 es: {imdm1c}")

        print(separador)
        print("Semestre 2")
        un_a_p2c = float(input("Dime las unidades a producir del semestre 2: "))
        hr_p_u2c = float(input("Dime las horas requeridas por unidad del semestre 2: "))
        ttlhr2c = (un_a_p2c * hr_p_u2c)
        print(f"El Total de horas requeridas del semestre 2 es: {ttlhr2c}")
        cuoph2c = float(input("Dime la cuota por hora del semestre 2: "))
        imdm2c = (ttlhr2c * cuoph2c)
        print(f"El Importe de M.O.D. del semestre 2 es: {imdm2c}")

        print(separador)
        print("Año")
        un_a_ptc = (un_a_p1c + un_a_p2c)
        hr_p_utc = (hr_p_u1c)
        ttlhrtc = (un_a_ptc * hr_p_utc)
        imdmtc = (imdm1c + imdm2c)
        print(f"El Total de horas requeridas del año es: {ttlhrtc}")
        print(f"El Importe de M.O.D. del año es: {imdmtc}")


        print(separador)
        print("Producto CR")
        print("Semestre 1")
        un_a_p1d = float(input("Dime las unidades a producir del semestre 1: "))
        hr_p_u1d = float(input("Dime las horas requeridas por unidad del semestre 1: "))
        ttlhr1d = (un_a_p1d * hr_p_u1d)
        print(f"El Total de horas requeridas del semestre 1 es: {ttlhr1d}")
        cuoph1d = float(input("Dime la cuota por hora del semestre 1: "))
        imdm1d = (ttlhr1d * cuoph1d)
        print(f"El Importe de M.O.D. del semestre 1 es: {imdm1d}")

        print(separador)
        print("Semestre 2")
        un_a_p2d = float(input("Dime las unidades a producir del semestre 2: "))
        hr_p_u2d = float(input("Dime las horas requeridas por unidad del semestre 2: "))
        ttlhr2d = (un_a_p2d * hr_p_u2d)
        print(f"El Total de horas requeridas del semestre 2 es: {ttlhr2d}")
        cuoph2d = float(input("Dime la cuota por hora del semestre 2: "))
        imdm2d = (ttlhr2d * cuoph2d)
        print(f"El Importe de M.O.D. del semestre 2 es: {imdm2d}")

        print(separador)
        print("Año")
        print("Año")
        un_a_ptd = (un_a_p1d + un_a_p2d)
        hr_p_utd = (hr_p_u1d)
        ttlhrtd = (un_a_ptd * hr_p_utd)
        imdmtd = (imdm1d + imdm2d)
        print(f"El Total de horas requeridas del año es: {ttlhrtd}")
        print(f"El Importe de M.O.D. del año es: {imdmtd}")

        print(f"Total de horas requeridas por semestre del semestre 1 es: {(ttlhr1 + ttlhr1c + ttlhr1d)}")
        print(f"Total de horas requeridas por semestre del semestre 2 es: {(ttlhr2 + ttlhr2c + ttlhr2d)}")
        print(f"Total de horas requeridas por semestre del año es: {(ttlhrt + ttlhrtc + ttlhrtd)}")

        print(f"Total de M.O.D. por semestre del semestre 1 es: {(imdm1 + imdm1c + imdm1d)}")
        print(f"Total de M.O.D. por semestre del semestre 2 es: {(imdm2 + imdm2c + imdm2d)}")
        print(f"Total de M.O.D. por semestre del año es: {(imdmt + imdmtc + imdmtd)}")


    elif opcion == 8:
        borrarPantalla()
        print(separador)
        print("-8- Presupuesto Indirecto de Fabricacion")
        print("Semestre 1")
        dep1 = int(input("Dime la depreciacion del semestre 1: "))
        seg1 = int(input("Dime el costo de seguros del semestre 1: "))
        mant1 = int(input("Dime el costo de Mantenimiento del semestre 1: "))
        ener1 = int(input("Dime el costo de energeticos del semestre 1: "))
        var1 = int(input("Dime los costos varios del semestre 1: "))
        ttls1 = (dep1 + seg1 + mant1 + ener1+ var1)
        print(f"Total G.I.F. del semestre 1 es: {ttls1}")
        print("Semestre 2")
        dep2 = int(input("Dime la depreciacion del semestre 2: "))
        seg2 = int(input("Dime el costo de seguros del semestre 2: "))
        mant2 = int(input("Dime el costo de mantenimiento del semestre 2: "))
        ener2 = int(input("Dime el costo de energeticos del semestre 2: "))
        var2 = int(input("Dime los costos varios del semestre 2: "))
        ttls2 = (dep2 + seg2 + mant2 + ener2 + var2)
        print("Total del año")
        dept = (dep1 + dep2)
        segt = (seg1 + seg2)
        mantt = (mant1 + mant2)
        enert = (ener1 + ener2)
        vart = (var1 + var2)
        ttlst = (dept + segt + mantt + enert + vart)
        print(f"Total G.I.F. del semestre 2 es: {ttls2}")
        print(f"Total G.I.F. del año es: {ttlst}")
        print("Coeficiente para determinar el costo por hora de gastos indirectos de fabricacion")
        print(f"Total de G.I.F {ttlst}")
        Tot_HrsAnual = int(input("Ingrese el Total de horas M.O.D. Anual: "))
        print(f"Costo por Hora de G.I.F. {ttlst/Tot_HrsAnual}, redondeado a 3.17")

    elif opcion == 9:
        borrarPantalla()
        print (separador)
        print("-9- Presupuesto de Gastos de Operacion")
        print("Semestre 1")
        dep1 = int(input("Dime la Depreciacion del semestre 1: "))
        sueysal1 = int(input("Dime los sueldos y salarios del semestre 1: "))
        com1 = int(input("Dime el costo de las comisiones del semestre 1: "))
        var1 = int(input("Dime los costos varios del semestre 1: "))
        intpo1 = int(input("Dime los interes por obligaciones del semestre 1: "))
        ttlgo1 = (dep1 + sueysal1 + com1 + var1 + intpo1)
        print(f"El total de Gastos de Operacion del semestre 1 es: {ttlgo1}")

        print(separador)
        print("Semestre 2")
        dep2 = int(input("Dime la Depreciacion del semestre 2: "))
        sueysal2 = int(input("Dime los sueldos y salarios del semestre 2: "))
        com2 = int(input("Dime el costo de las comisiones del semestre 2: "))
        var2 = int(input("Dime los costos varios del semestre 2: "))
        intpo2 = int(input("Dime los interes por obligaciones del semestre 2: "))
        ttlgo2 = (dep2 + sueysal2 + com2 + var2 + intpo2)
        print(f"El total de Gastos de Operacion del semestre 2 es: {ttlgo2}")

        print(separador)
        print("Año")
        dept = (dep1 + dep2)
        sueysalt = (sueysal1 + sueysal2)
        comt = (com1 + com2)
        vart = (var1 + var2)
        intpot = (intpo1 + intpo2)
        ttlgot = (dept + sueysalt + comt + vart + intpot)
        print(f"El total de Gastos de Operacion del año es: {ttlgot}")

    elif opcion == 10:
        borrarPantalla()
        print("-10- Determinacion del Costo Unitario de Productos Terminados")
        MaterialA = float
        MateriaB = float
        MaterialC = float
        ManoDeObra = float
        GasIndeFab = float
        CostoUnitario = float

        print("----------------PRODUCTO CL------------")

        print("---COSTO---")
        CosCLMaterialA = 12.00
        CosCLMaterialB = 3.00
        CosCLMaterialC = 2.00
        CosCLManoDeObra = 18.00
        CosCLGasIndeFab = 3.17
        print("Costo Material de Material A Producto CL: 12.00")
        print("Costo Material de Material B Producto CL: 3.00")
        print("Costo Material de Material C Producto CL: 2.00")
        print("Costo Material de Mano de Obra Producto CL: 18.00")
        print("Costo Material de Gasto Indirectos Producto CL: 3.17")


        print("---CANTIDAD---")
        CanCLMaterialA = 1.00
        CanCLMaterialB = 0.50
        CanCLMaterialC = 10.00
        CanCLManoDeObra = 2.00
        CanCLGasIndeFab = 2.00
        print("Cantidad Material A: 1.00")
        print("Cantidad Material B: 0.50")
        print("Cantidad Material C: 10.00")
        print("Cantidad Mano de Obra: 2.00")
        print("Cantidad Gastos Indirectos: 2.00")


        print("---COSTO UNITARIO---")
        CuCLMaterialA = 12.00
        CuCLMaterialB = 1.50
        CuCLMaterialC = 20.00
        CuCLManoDeObra = 36.00
        print("Costo Unitario Material A: 12.00")
        print("Costo Unitario Material B: 1.50")
        print("Costo Unitario Material C: 20.00")
        print("Costo Unitario Mano de obra: 36.00")
        CuCLGasIndeFab = float (input("Dime el costo unitario de la gastos indirectos de fabricacion: "))
        print("COSTO UNITARIO RESULTADO")
        print (f"El resultado del costo unitario del producto CL es: {(CuCLMaterialA + CuCLMaterialB + CuCLMaterialC + CuCLManoDeObra + CuCLGasIndeFab)}")



        print("---------------PRODUCTO CE--------------")

        print("COSTO")
        CosCEMaterialA = 12.00
        CosCEMaterialB = 3.00
        CosCEMaterialC = 3.00
        CosCEManoDeObra = 18.00
        CosCEGasIndeFab = 3.17

        print("CANTIDAD")
        CanCEMaterialA = float(input("Dime la cantidad del Material A: "))
        CanCEMaterialB = float(input("Dime la cantidad del Material B: "))
        CanCEMaterialC = float(input("Dime la cantidad del Material C: "))
        CanCEManoDeObra = float(input("Dime la cantidad de la Mano de obra: "))
        CanCEGasIndeFab = float(input("Dime la cantidad de gastos indirectos: "))

        print("COSTO UNITARIO")
        CuCEMaterialA = float(input("Dime el costo unitario del Material A: "))
        CuCEMaterialB = float(input("Dime el costo unitario del Material B: "))
        CuCEMaterialC = float(input("Dime el costo unitario del Material C: "))
        CuCEManoDeObra = float(input("Dime el costo unitario de la mano de obra: "))
        CuCEGasIndeFab = float (input("Dime el costo unitario de la gastos indirectos: "))
        print("COSTO UNITARIO RESULTADO")
        print (f"El resultado del costo unitario del producto CE es: {(CuCEMaterialA + CuCEMaterialB + CuCEMaterialC + CuCEManoDeObra + CuCEGasIndeFab)}")



        print("---------------PRODUCTO CR--------------")

        print("COSTO")
        CosCRMaterialA = 12.00
        CosCRMaterialB = 3.00
        CosCRMaterialC = 3.00
        CosCRManoDeObra = 18.00
        CosCRGasIndeFab = 3.17

        print("CANTIDAD")
        CanCRMaterialA = float(input("Dime la cantidad del Material A: "))
        CanCRMaterialB = float(input("Dime la cantidad del Material B: "))
        CanCRMaterialC = float(input("Dime la cantidad del Material C: "))
        CanCRManoDeObra = float(input("Dime la cantidad de la Mano de obra: "))
        CanCRGasIndeFab = float(input("Dime la cantidad de gastos indirectos: "))

        print("COSTO UNITARIO")
        CuCRMaterialA = float(input("Dime el costo unitario del Material A: "))
        CuCRMaterialB = float(input("Dime el costo unitario del Material B: "))
        CuCRMaterialC = float(input("Dime el costo unitario del Material C: "))
        CuCRManoDeObra = float(input("Dime el costo unitario de la mano de obra: "))
        CuCRGasIndeFab = float (input("Dime el costo unitario de la gastos indirectos: "))
        print("COSTO UNITARIO RESULTADO")
        print (f"El resultado del costo unitario del producto CE es: {(CuCRMaterialA + CuCRMaterialB + CuCRMaterialC + CuCRManoDeObra + CuCRGasIndeFab)}")


    elif opcion == 11:
        borrarPantalla()
        print ("-11- Valuacion de Inventario Finales")
        print("-----Inventario Final de Materiales-----")

        print("---UNIDADES---")
        UniMatA = int(input("Ingrese Unidades de Material A: "))
        CuMatA = float(input("Ingrese el Costo Unitario Material A: "))
        costo_totalA = (UniMatA *CuMatA)
        print(f"Costo total: {costo_totalA}")

        UniMatB = int(input("Ingrese Unidades de Material B: "))
        CuMatB = float(input("Ingrese el Costo Unitario Material B: "))
        costo_totalB = (UniMatB *CuMatB)
        print(f"Costo total: {costo_totalB}")

        UniMatC = int(input("Ingrese Unidades de Material c: "))
        CuMatC = float(input("Ingrese el Costo Unitario Material C: "))
        costo_totalC = (UniMatC *CuMatC)
        print(f"Costo total: {costo_totalC}")
        print(f"Inventario final de materiales: {costo_totalA + costo_totalB + costo_totalC}")

        print("-----Inventario Final de Producto Terminado-----")
        PCL = int(input("Ingrese Unidades del Producto CL: "))
        CUCL = float(input("Ingrese costo unitario del Producto CL"))
        costo_CL = (PCL * CUCL)
        print(f"Costo total: {costo_CL}")
        PCE = int(input("Ingrese Unidades del Producto CE: "))
        CUCE = float(input("Ingrese costo unitario del Producto CE"))
        costo_CE = (PCE * CUCE)
        print(f"Costo total: {costo_CE}")
        PCR = int(input("Ingrese Unidades del Producto CR: "))
        CUCR = float(input("Ingrese costo unitario del Producto CR"))
        costo_CR = (PCR * CUCR)
        print(f"Costo total: {costo_CR}")
        print(f"Inventario final de producto terminado: {costo_CL + costo_CE + costo_CR}")

    elif opcion == 12:
        borrarPantalla()
        print("-Estado de Costo de Produccion y Ventas-")
        SI_Mat = int(input("Ingrese el Saldo Inicial de Materiales: "))
        Compras_Mat = int(input("Ingrese Compras de Materiales: "))
        mat_Disponible = (SI_Mat + Compras_Mat)
        print(f"(=)Materiales Disponibles: {mat_Disponible}")
        Invet_Final = int(input("Ingrese Inventario Final de Materiales: "))
        Mat_Utilizados = (mat_Disponible - Invet_Final)
        print(f"(=)Materiales Utilizados: {Mat_Utilizados}")
        MOD = int(input("Ingrese Mano de Obra Directa: "))
        GIF = int(input("Ingrese Gastos de Fabricacion Indirectos: "))
        Costo_P = (Mat_Utilizados + MOD + GIF)
        print(f"(=)Costo de Produccion: {Costo_P}")
        Invet_Inicial = int(input("Ingrese Inventario Inicial de Productos Terminados: "))
        tot_PDisp = (Costo_P + Invet_Inicial)
        print(f"(=)Total de Produccion Disponible: {tot_PDisp}")
        InventarioFinal_PT = int(input("Ingrese Inventario Final de Productos Terminados: "))
        print(f"(=)Costo de Ventas: {tot_PDisp - InventarioFinal_PT}")


    elif opcion == 13:
        borrarPantalla()
        print("-Estado de Resultados-")
        Ventas = int(input("Ingrese Ventas: "))
        Costo_Ventas = int(input("Ingrese Costo de Ventas: "))
        Ut_Bruta = (Ventas - Costo_Ventas)
        print(f"(=) Utilidad Bruta: {Ut_Bruta}")
        Gastos_Op = int(input("Ingrese Gastos de Operacion: "))
        Utilidad_Op = (Ut_Bruta - Gastos_Op)
        print(f"(=)Utilidad de Operacion: {Utilidad_Op}")
        ISR = int(input("Ingrese ISR: "))
        PTU = int(input("Ingrese PTU: "))
        print(f"Utilidad Neta: {Utilidad_Op - ISR - PTU}")

    elif opcion == 14:
        borrarPantalla()
        print("-Estado de Flujo de Efectivo-")
        SaldoInicial = float(input("Dime el saldo inicial: "))
        Cobranza2016 = float(input("Dime la cantidad de la cobranza del año 2016: "))
        Cobranza2015 = float(input("Dime la cantidad de la cobranza del año 2015: "))
        print (f"Total de entradas: {(Cobranza2016 + Cobranza2015 )}")
        efec_disponible = (Cobranza2016 + Cobranza2015 + SaldoInicial)
        print(f"Efectivo Disponible: {efec_disponible}")

        Provedores2016 = float(input("Dime el saldo de Provedores en 2016: "))
        Provedores2015 = float(input("Dime el saldo de Provedores en 2015: "))
        PagoManoDeObraDir = float(input("Dime el presupuesto de Mano de Obra Directa: "))
        PagoGasIndFabricaion = float(input("Dime el presupuesto de Gastos Indirectos de Fabricacion: "))
        PagoGasOperacion = float(input("Dime el presupuesto de gastos de operacion: "))
        CompraActivoFijo = float(input("Dime la cantidad de Compra de Activo Fijo: "))
        PagoISR2015 = float(input("Dime el pago ISR del año 2015: "))
        tot_salidas = (Provedores2016 + Provedores2015 + PagoManoDeObraDir + PagoGasIndFabricaion + PagoGasOperacion + CompraActivoFijo + PagoISR2015)
        print(f"Total de salidas: {tot_salidas}")
        print(f"Flujo de Efectivo Actual: {efec_disponible - tot_salidas}")

    elif opcion == 15:
        borrarPantalla()
        print("-Balance General-")
        print("Activo")
        print("Circulante")
        efec = float(input("Dime  el efectivo: "))
        cli = float(input("Dime el valor de clientes: "))
        deud = float(input("Dime el valor de deudores diversos: "))
        funyemp = float(input("Dime el valor de funcionarios y empleados: "))
        invdm = float(input("Dime el valor de inventario de materiales: "))
        invdpt = float(input("Dime el valor de inventario de producto terminado: "))
        ttldac = (efec + cli +deud + funyemp + invdm + invdpt )
        print(f"El total de activos circulantes es: {ttldac}")
        print(separador)

        print("No Circulante")
        ter = float(input("Dime  el terreno: "))
        pye = float(input("Dime el valor de planta y equipo: "))
        deacu = float(input("Dime el valor de depreciacion acumulada: "))
        ttldanc = (ter + pye + deacu)
        print(f"El total de activos no circulantes es: {ttldanc}")
        print(separador)
        ttlda = (ttldac + ttldanc)
        print(f"El total de activos  es: {ttlda}")
        print(separador)

        print("Pasivo")
        print("Corto Plazo")
        prov = float(input("Dime  el valor de proveedores: "))
        docpp = float(input("Dime el valor de documentos por pagar: "))
        irspp = float(input("Dime el valor de IRS por pagar: "))
        ptupp = float(input("Dime el valor de PTU por pagar: "))
        ttldpcp = (prov + docpp + irspp + ptupp)
        print(f"El total de pasivos corto plazo es: {ttldpcp}")
        print(separador)

        print("Largo Plazo")
        obpp = float(input("Dime  el valor de obligaciones por pagar: "))
        ttldplp = (obpp)
        print(f"El total de pasivos largo plazo es: {ttldplp}")

        print(separador)
        ttldp = (ttldpcp + ttldplp)
        print(f"El total de pasivo  es: {ttldp}")
        print(separador)

        print("Capital Contable")
        ca = float(input("Dime  el valor de capital aportado: "))
        cg = float(input("Dime el valor de capital ganado: "))
        utde = float(input("Dime el valor de utilidad del ejercicio: "))
        ttldcp = (ca + cg + utde)
        print(f"El total de capital contable  es: {ttldcp}")
        print(separador)
        sudpyc = (ttldcp + ttldp)
        print(f"El total de la suma de pasivo y capital   es: {sudpyc}")

    elif opcion == 0:
        print("--Fin del programa--")
        break
    else:
        print("Ha introducido una opcion invalida")




